name: Generate Manifest

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

env:
  TAG: ${{ github.event.inputs.tag_name || github.event.inputs.tag_name }}

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate manifest
        run: node ./scripts/generate-manifest.js ${{ env.TAG }}

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "Upsy Automation"
          git config user.email "support@upsyshopping.com"
          git checkout -b release
          git add manifest.json
          git commit -m "Update manifest.json for release ${{ env.TAG }}"
          git push --force origin release