name: Generate Manifest

on:
  release:
    types: [published]

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate manifest
        run: node ./scripts/generate-manifest.js ${{ github.event.release.tag_name }}

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "Upsy Automation"
          git config user.email "support@upsyshopping.com"
          git checkout -b release
          git add manifest.json
          git commit -m "Update manifest.json for release ${{ github.event.release.tag_name }}"
          git push --force origin gh-pages