name: Archive and Upload to Google Drive
on:
  push:
    branches:
      - main
      - master
      - gdrive-upload-workflow-test

jobs:
  zip-master-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install zip package if not available
        run: |
          if ! which zip > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y zip
          else
            echo "Zip package already available"
          fi
      - name: Archive files
        run: |
          echo "Start acrhive master branch"
          zip -r archive.zip *
          echo "Complete archive of master branch"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: upsy-woo-plugin
          path: archive.zip
  
  download-artifact-and-upload-to-google-drive:
    needs: [zip-master-branch]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: upsy-woo-plugin
          path: .
      
      - name: Install wget if not exists
        run: |
          if ! which wget > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y wget
            echo "which wget"
          else
            echo "wget already available"
          fi
      
      - name: Install base64 if not available
        run: |
          if ! which base64 >/dev/null; then
            echo "base64 is not available"
            sudo apt-get update
            sudo apt-get install -y coreutils
          else
            echo "base64 already available"
          fi

      - name: Install prasmussen/gdrive
        run: |
          if [ -e ./gdrive ]; then
          echo "The file gdrive exists in the current directory."
          else
          echo "The file gdrive does not exist in the current directory."
          wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
          tar -xzvf gdrive_2.1.1_linux_386.tar.gz
          chmod +x gdrive
          fi
    
      - name: Decode and write secret to file
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | base64 --decode > key.json
      
      - name: Upload acrhive to google drive
        run: |
          echo "Before upload directory list...."
          ./gdrive list --config $(pwd) --service-account key.json --query ""
          ./gdrive upload  --config $(pwd) --service-account key.json -p ${{secrets.GOOGLE_DRIVE_FOLDER_ID}} --name myfile_new.zip archive.zip
          echo "After upload directory list:"
          ./gdrive list --config $(pwd) --service-account key.json --query ""
          echo "Upload completed"
    
      - name : Remove generated files(key, artifact)
        run: |
          rm -rf key.json archive.zip

          


      # - name: Upload to gdrive
      #   uses: willo32/google-drive-upload-action@v1
      #   with: 
      #     target: archive.zip
      #     credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          