name: Archive and Upload to Google Drive
on:
  push:
    branches:
      - main
      - master
      - gdrive-upload-workflow-test


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "hello world"