name: Archive and Upload to Google Drive
on:
  push:
    branches:
      - main
      - master
      - gdrive-upload-workflow-test

env:
  ARTIFACT_NAME: upsy-woocommerce-plugin.zip
  GDRIVE_DOWNLOAD_LINK: https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
  KEY_FILENAME: key.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install zip package if not available
        run: |
          if ! which zip > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y zip
          fi

      - name: Archive files
        run: |
          zip -r ${{env.ARTIFACT_NAME}} *
          ls -lah

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_NAME}}
  
  upload:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .
      
      - name: Install wget if not exists
        run: |
          if ! which wget > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y wget
          fi
      
      - name: Install base64 if not available
        run: |
          if ! which base64 >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y coreutils
          fi

      - name: List cache contents
        run: |
          if test -e ${{runner.workspace}}/.cache > /dev/null; then
            ls -R ${{ runner.workspace }}/.cache
          else
            echo "${{runner.workspace}}/.cache does not exits"
          fi

      - name: Install prasmussen/gdrive
        run: |
            wget -O gdrive ${{env.GDRIVE_DOWNLOAD_LINK}}
            tar -xzvf gdrive
            chmod +x gdrive
            mv -f gdrive /usr/local/bin/
      - name: Cache gdrive
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/gdrive
          key: ${{ runner.os }}-gdrive
    
      - name: Decode and write secret to file
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | base64 --decode \
          > ${{env.KEY_FILENAME}}
      
      - name: Upload acrhive to google drive
        run: |
          # gdrive upload \
          # --config $(pwd) \
          # --service-account ${{env.KEY_FILENAME}} \
          # --delete -p ${{secrets.GOOGLE_DRIVE_FOLDER_ID}} \
          # --name ${{env.ARTIFACT_NAME}} ${{env.ARTIFACT_NAME}}

          file_ids=$(gdrive list --config $(pwd) --service-account ${{env.KEY_FILENAME}} -q "'${{secrets.GOOGLE_DRIVE_FOLDER_ID}}' in parents and mimeType != 'application/vnd.google-apps.folder'" | awk '{if (NR>1) {print $1}}')
          
          old_dir_id=$(gdrive list --config $(pwd) --service-account ${{env.KEY_FILENAME}} -q "'${{secrets.GOOGLE_DRIVE_FOLDER_ID}}' in parents and name='old'" | awk 'NR==2{print $1}')
          
          for id in $file_ids; do
            echo "file id is $id"
            gdrive move --config $(pwd) --service-account ${{env.KEY_FILENAME}} $id --parent $old_dir_id
          done

      - name : Remove generated files(key, artifact)
        run: |
          rm -rf ${{env.KEY_FILENAME}} ${{env.ARTIFACT_NAME}}