name: Archive and Upload to Google Drive
on:
  push:
    branches:
      - main
      - master
      - gdrive-upload-workflow-test
env:
  CREDENTIALS_FILE: credentials.json
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set artifact name env
        run: |
          echo "ARTIFACT_NAME=$(basename ${{github.workspace}})-${{github.ref_name}}.zip" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref_name}}
      
      - name: Install zip package if not available
        run: |
          if ! which zip > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y zip
          fi
        
      - name: Install base64 if not exits
        run: |
          if ! which base64 >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y coreutils
          fi
        
      - name: Archive files
        run: |
          zip -r "${{env.ARTIFACT_NAME}}" *
          ls -lah
        
      - name: Decode and write secret to file
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | base64 --decode \
          > ${{env.CREDENTIALS_FILE}}

      - name: Set up Python 3.10
        uses: actions/setup-python@master
        with:
          python-version: 3.10.6
        
      - name: Install python script dependencies
        run: |
          which python
          python --version
          pip install requests
          pip install -r scripts/requirements.txt
    
      - name: Upload
        run: |
          python scripts/upload.py\
            --credentials-file ${{env.CREDENTIALS_FILE}}\
            --parent-folder-id ${{secrets.GOOGLE_DRIVE_FOLDER_ID}}\
            --destination-folder-id ${{secrets.GOOGLE_DRIVE_DESTINATION_FOLDER_ID}}\
            --upload-filename ${{env.ARTIFACT_NAME}}\
            --upload-filepath ${{env.ARTIFACT_NAME}}
      

      

