name: Archive and Upload to Google Drive
on:
  push:
    branches:
      - main
      - master
      - gdrive-upload-workflow-test

jobs:
  zip-master-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          echo "Start acrhive master branch"
          zip -r archive.zip *
          echo "Complete archive of master branch"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: upsy-woo-plugin
          path: archive.zip
  
  download-artifact-and-upload-to-google-drive:
    needs: [zip-master-branch]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: upsy-woo-plugin
          path: .
      
      - name: Install wget
        run: sudo apt-get update && sudo apt-get install -y wget
      - name: Install gdrive
      
        run: |
          if [ -e gdrive ]; then
          echo "The file gdrive exists in the current directory."
          else
          echo "The file gdrive does not exist in the current directory."
          wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
          tar -xzvf gdrive_2.1.1_linux_386.tar.gz
          chmod +x gdrive
          fi
      - name: Install base64 if not available
        run: |
          if ! which base64 >/dev/null 2>&1; then
            echo "base64 is not available"
            sudo apt-get update
            sudo apt-get install -y coreutils
          fi
      - name: Decode and write secret to file
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | base64 --decode > key.json
          cat key.json
      - name: Upload acrhive to google drive
        run: |
          pwd
          ls -la $pwd
          mkdir -p /home/runner/.gdrive && mv -f key.json /home/runner/.gdrive/
          mv -f archive.zip /home/runner/.gdrive/

          ./gdrive upload --service-account key.json /home/runner/.gdrive/archive.zip
          ./gdrive list --service-account key.json
          echo "Upload completed"

          


      # - name: Upload to gdrive
      #   uses: willo32/google-drive-upload-action@v1
      #   with: 
      #     target: archive.zip
      #     credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          