name: Archive and Upload to Google Drive
on:
  push:
    branches:
      - main
      - master
      - gdrive-upload-workflow-test

jobs:
  zip-master-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          echo "Start acrhive master branch"
          zip -r archive.zip *
          echo "Complete archive of master branch"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: upsy-woo-plugin
          path: archive.zip
  
  download-artifact-and-upload-to-google-drive:
    needs: [zip-master-branch]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: upsy-woo-plugin
          path: .
      
      # - name: Install wget
      #   run: sudo apt-get update && sudo apt-get install -y wget
      # - name: Install gdrive
      #   if: "! test -f gdrive"
      #   run: |
      #     wget -O gdrive  https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_amd64.tar.gz
      #     tar -xzvf gdrive
      #     chmod +x gdrive
      - name: Upload to gdrive
        uses: willo32/google-drive-upload-action@v1
        with: 
          target: archive.zip
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }} 