name: Archive and Upload to Google Drive
on:
  push:
    branches:
      - main
      - master
      - gdrive-upload-workflow-test

env:
  ARTIFACT_NAME: upsy-woocommerce-plugin.zip
  GDRIVE_DOWNLOAD_LINK: https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
  KEY_FILENAME: key.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install zip package if not available
        run: |
          if ! which zip > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y zip
          fi

      - name: Archive files
        run: |
          zip -r $ARTIFACT_NAME *

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: $ARTIFACT_NAME
          path: $ARTIFACT_NAME
  
  upload:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: $ARTIFACT_NAME
          path: .
      
      - name: Install wget if not exists
        run: |
          if ! which wget > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y wget
          fi
      
      - name: Install base64 if not available
        run: |
          if ! which base64 >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y coreutils
          fi

      - name: Install prasmussen/gdrive
        run: |
          if ! test -e /usr/bin/gdrive; then
            echo -e "gdrive not exits\n"
            echo -e "Downloading gdrive from $GDRIVE_DOWNLOAD_LINK\n"
            wget -O gdrive $GDRIVE_DOWNLOAD_LINK
            tar -xzvf gdrive
            mv -f gdrive /usr/bin/
            chmod +x /usr/bin/gdrive
          else
            echo "Gdrive exists.."
          fi
    
      - name: Decode and write secret to file
        run: |
          cat ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }} | base64 --decode > $KEY_FILENAME
      
      - name: Upload acrhive to google drive
        run: |
          which gdrive
          echo -e "which gdrive\n"
          gdrive list --config $(pwd) --service-account $KEY_FILENAME --query ""
          gdrive upload  --config $(pwd) --service-account $KEY_FILENAME -p ${{secrets.GOOGLE_DRIVE_FOLDER_ID}} --name myfile_new.zip $ARTIFACT_NAME
          gdrive list --config $(pwd) --service-account $KEY_FILENAME --query ""
    
      - name : Remove generated files(key, artifact)
        run: |
          rm -rf $KEY_FILENAME $ARTIFACT_NAME